### ISSUE TITLE
Testcases failed when the user is root (e.g., in the Docker environment)

### ISSUE THREAD

**Issue by mssun** [uutils/coreutils#1138]
I tried to run `make test` in a Docker container environment (CI), and some failed. Basically, these testcases assume that the user is never a root user.

```
failures:

---- test_chgrp::test_1 stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils chgrp bin /tmp
thread 'test_chgrp::test_1' panicked at 'assertion failed: !self.success', tests/common/util.rs:65:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- test_chgrp::test_big_p stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils chgrp -RP bin /proc/self/cwd
thread 'test_chgrp::test_big_p' panicked at 'assertion failed: !self.success', tests/common/util.rs:65:9

---- test_chgrp::test_fail_silently stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils chgrp -f bin /tmp
thread 'test_chgrp::test_fail_silently' panicked at 'assertion failed: !self.success', tests/common/util.rs:147:9

---- test_chgrp::test_big_h stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils chgrp -RH bin /proc/self/fd
thread 'test_chgrp::test_big_h' panicked at 'assertion failed: new_ucmd!().arg("-RH").arg("bin").arg("/proc/self/fd").fails().stderr.lines().fold(0,
                                                                                   |acc,
                                                                                    _|
                                                                                       acc
                                                                                           +
                                                                                           1)
    > 1', tests/test_chgrp.rs:130:5

---- test_chgrp::test_reference stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils chgrp -v --reference=/etc/passwd /etc
thread 'test_chgrp::test_reference' panicked at 'assertion failed: !self.success', tests/common/util.rs:65:9

---- test_who::test_heading stdout ----
        current_directory_resolved:
run: /mesalock-linux/mesalock-distro/build/src/uutils-coreutils/target/debug/uutils who -H
current_directory_resolved:
run: who -H
thread 'test_who::test_heading' panicked at 'assertion failed: `(left == right)`
  left: `"NAME     LINE         TIME         COMMENT"`,
 right: `"NAME     LINE         TIME             COMMENT"`', tests/common/util.rs:94:9


failures:
    test_chgrp::test_1
    test_chgrp::test_big_h
    test_chgrp::test_big_p
    test_chgrp::test_fail_silently
    test_chgrp::test_reference
    test_who::test_heading

test result: FAILED. 541 passed; 6 failed; 12 ignored; 0 measured; 0 filtered out

Makefile:278: recipe for target 'test' failed
```

**Comment by Arcterus** [comment]
Which Docker container was it?  I'll fix this after my upcoming midterms.

**Comment by mssun** [comment]
I think it is because you are root inside a container. You can reproduce the cases easily by:

```
$ docker run --rm -it rust
# apt-get update && apt-get cmake
# git clone https://github.com/uutils/coreutils.git && cd coreutils
# cargo tests
```

**Comment by Arcterus** [comment]
Alright, thanks.  I'll look at it when I get a chance.
