### ISSUE TITLE
`stdbuf` failing to compile

### ISSUE THREAD

**Issue by nothingnesses** [uutils/coreutils#1276]
After running `export RUST_BACKTRACE=1 && export CXX=/usr/bin/clang++ && stdbuf -o 0 cargo +nightly install --git https://github.com/uutils/coreutils.git --features "arch base32 base64 basename cat chgrp chmod chown chroot cksum comm cut dircolors dirname du echo env expand factor false fmt fold groups hashsum head hostid hostname id kill link ln logname mkdir mkfifo mknod mktemp mv nice nl nohup nproc numfmt paste pathchk pinky printenv ptx pwd readlink realpath relpath rm rmdir seq shred shuf sleep stat stdbuf sum sync tac tee timeout touch tr true truncate tsort tty uname unexpand uniq unlink uptime users wc who whoami yes" uutils --no-default-features &| tee /data/output.txt`, the process fails with this output:

```
    Updating git repository `https://github.com/uutils/coreutils.git`
  Installing uutils v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling cc v1.0.6
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling libc v0.2.42
   Compiling lazy_static v1.0.1
   Compiling rustc-demangle v0.1.8
   Compiling cfg-if v0.1.2
   Compiling unicode-width v0.1.5
   Compiling byteorder v1.2.1
   Compiling typenum v1.10.0
   Compiling pkg-config v0.3.9
   Compiling data-encoding v2.1.1
   Compiling void v1.0.2
   Compiling winapi v0.3.5
   Compiling winapi-build v0.1.1
   Compiling nodrop v0.1.12
   Compiling regex v1.0.1
   Compiling byte-tools v0.2.0
   Compiling num-traits v0.2.1
   Compiling ucd-util v0.1.1
   Compiling head v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling mkdir v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling env v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling echo v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling expr v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling bitflags v1.0.1
   Compiling touch v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling truncate v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling logname v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling basename v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling uniq v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling dircolors v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling test v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling tee v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling numfmt v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling paste v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling true v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling nl v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling uname v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling printf v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling arch v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling groups v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling id v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling expand v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling split v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling fmt v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling whoami v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling either v1.4.0
   Compiling sleep v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling nproc v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling ls v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling chroot v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling wc v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling sync v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling more v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling date v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling unexpand v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling mv v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling hashsum v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling tac v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling uptime v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling users v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling pathchk v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling nice v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling sort v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling tsort v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling shred v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling dirname v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling base64 v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling seq v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling shuf v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling kill v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling remove_dir_all v0.5.1
   Compiling factor v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling ptx v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling join v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling hostid v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling fold v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling chown v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling yes v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling bit-vec v0.5.0
   Compiling tr v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling same-file v1.0.2
   Compiling du v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling stat v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling realpath v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling chmod v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling chgrp v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling winapi v0.2.8
   Compiling link v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling rmdir v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling vec_map v0.8.0
   Compiling cp v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling base32 v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling pinky v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling tty v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling ln v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling who v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling utf8-ranges v1.0.0
   Compiling mktemp v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling fake-simd v0.1.2
   Compiling cksum v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling hostname v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling timeout v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling relpath v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling nohup v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling cut v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling strsim v0.7.0
   Compiling mknod v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling install v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling rm v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling false v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling od v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling comm v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling pwd v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling semver-parser v0.7.0
   Compiling unlink v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling mkfifo v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling sum v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling printenv v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling readlink v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling cat v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling ansi_term v0.11.0
   Compiling tail v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling bitflags v0.7.0
   Compiling fnv v1.0.6
   Compiling walker v1.0.1
   Compiling md5 v0.3.7
   Compiling sha1 v0.6.0
   Compiling half v1.1.1
   Compiling ioctl-sys v0.5.2
   Compiling hex v0.2.0
   Compiling glob v0.2.11
   Compiling uutils v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling quick-error v1.2.2
   Compiling cpp_synom v0.12.0
   Compiling synom v0.11.3
   Compiling memchr v1.0.2
   Compiling memchr v2.0.1
   Compiling time v0.1.40
   Compiling rand v0.4.2
   Compiling atty v0.2.8
   Compiling num_cpus v1.8.0
   Compiling xattr v0.2.1
   Compiling unix_socket v0.5.0
   Compiling filetime v0.2.1
   Compiling getopts v0.2.18
   Compiling textwrap v0.10.0
   Compiling term_grid v0.1.7
   Compiling unreachable v1.0.0
   Compiling advapi32-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling backtrace-sys v0.1.16
   Compiling cmake v0.1.29
   Compiling regex-syntax v0.6.1
   Compiling num-integer v0.1.36
   Compiling itertools v0.7.8
   Compiling walkdir v2.1.4
   Compiling bit-set v0.5.0
   Compiling semver v0.9.0
   Compiling nix v0.8.1
   Compiling syn v0.11.11
   Compiling cpp_syn v0.12.0
   Compiling aho-corasick v0.6.5
   Compiling termsize v0.1.5
   Compiling rand v0.3.22
   Compiling tempdir v0.3.7
   Compiling thread_local v0.3.5
   Compiling clap v2.32.0
   Compiling pretty-bytes v0.2.2
   Compiling onig_sys v67.1.0
   Compiling chrono v0.4.4
   Compiling synstructure v0.6.1
   Compiling tempfile v2.2.0
   Compiling cpp_synmap v0.3.0
   Compiling cpp_common v0.4.0
   Compiling platform-info v0.1.0 (https://github.com/uutils/platform-info#d8f49779)
   Compiling generic-array v0.8.3
   Compiling failure_derive v0.1.1
   Compiling cpp_macros v0.4.0
   Compiling digest v0.6.2
   Compiling block-buffer v0.2.0
   Compiling backtrace v0.3.7
   Compiling cpp_build v0.4.0
   Compiling sha3 v0.6.0
   Compiling sha2 v0.6.0
   Compiling onig v3.1.1
   Compiling failure v0.1.1
   Compiling libstdbuf v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling uucore v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
   Compiling cpp v0.4.0
   Compiling stdbuf v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)
error: failed to run custom build command for `stdbuf v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)`
process didn't exit successfully: `/tmp/cargo-installXlimxs/release/build/stdbuf-073e3d5775848fce/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("the source path is not an existing regular file") }', libcore/result.rs:983:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
             at ../csu/libc-start.c:308
  16: _start
             at ../sysdeps/x86_64/start.S:120

warning: build failed, waiting for other jobs to finish...
error: failed to compile `uutils v0.0.1 (https://github.com/uutils/coreutils.git#07b01a85)`, intermediate artifacts can be found at `/tmp/cargo-installXlimxs`

Caused by:
  build failed
```

**Comment by Arcterus** [comment]
Does it work if you clone the repository and then build?

**Comment by Arcterus** [comment]
Yeah it's due to the build setup for `stdbuf`.  IIRC it's because the structure of `target/` differs when using `--git` as compared to a normal build for some reason.

**Comment by VoidNoire** [comment]
I see, so this is a problem with `cargo` and not `stdbuf` then right? Shall I close this issue then? Also, do you know if there's already a relevant open issue on https://github.com/rust-lang/cargo pertaining to this one, and if not maybe it would be a good idea to open one right?

**Comment by Arcterus** [comment]
Sorry for taking so long to respond.  We could work around the issue in Cargo, so I think leaving this open is fine (at least for now).  I _believe_ there is already an open issue in Cargo, but I'm not 100% sure.

**Comment by tertsdiepraam** [comment]
I was expecting to find that this issue had been resolved somehow either by a patch to `cargo` or changes in `uutils`, but surprisingly that is not the case
