### ISSUE TITLE
sort panic

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1608]
I tried to do a command like this:

```
git log | grep Author | uniq -c | sort -k 1
```

and got the following stack trace:

```
git log ./src/net | egrep 'Author|Reviewed' | sort | uniq -c | sort -k 1
sort: error: Invalid options
Unrecognized option: 'k'
uniq: error: Broken pipe (os error 32)
sort: error: sort: Broken pipe (os error 32)
thread 'main' panicked at 'Write failed', src/uu/sort/src/sort.rs:555:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's fine that `-k` is not a valid option for sort, but I assume that you don't want the coreutils code to panic anywhere, and it did, hence the error report. I am using a Mac with commit aa1285e30585213e805d9381eaf1d57c88ea189b.

**Comment by kevinburkemeter** [comment]
Apologies, I didn't diagnose the problem correctly. The panic is coming from the first `sort` invocation, not the second.

```
$ git log ./src/net | egrep 'Author|Reviewed' | RUST_BACKTRACE=1 sort | uniq -c | sort -k 1
sort: error: Invalid options
Unrecognized option: 'k'
uniq: error: Broken pipe (os error 32)
sort: error: sort: Broken pipe (os error 32)
thread 'main' panicked at 'Write failed', src/uu/sort/src/sort.rs:555:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: uu_sort::exec
   8: uu_sort::uumain
   9: sort::main
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal
  12: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
