### ISSUE TITLE
Windows 10 errors

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#1747]
x86_64, Win 10 Pro v 10.0.19042 Build 19042, , commit 5935876f38 ,  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.52.0-nightly (3e826bb11 2021-02-21)

```bash

---- test_ls::test_ls_human stdout ----
current_directory_resolved:
run: truncate -s +1000 test_human
thread 'test_ls::test_ls_human' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', tests\common\util.rs:562:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_mktemp::test_mktemp_directory_tmpdir stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp --directory --tmpdir apt-key-gpghome.XXXXXXXXXX
thread 'test_mktemp::test_mktemp_directory_tmpdir' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9

---- test_mktemp::test_mktemp_make_temp_dir stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp -d tempXXXXXX
thread 'test_mktemp::test_mktemp_make_temp_dir' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9

---- test_mktemp::test_mktemp_mktemp stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp tempXXXXXX
thread 'test_mktemp::test_mktemp_mktemp' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9

---- test_mktemp::test_mktemp_mktemp_t stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp -t tempXXXXXX
thread 'test_mktemp::test_mktemp_mktemp_t' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9

---- test_mktemp::test_mktemp_suffix stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp --suffix suf tempXXXXXX
thread 'test_mktemp::test_mktemp_suffix' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9

---- test_mktemp::test_mktemp_tmpdir_one_arg stdout ----
current_directory_resolved:
run: C:\Users\chad\github\coreutils\target\debug\coreutils.exe mktemp --tmpdir apt-key-gpghome.XXXXXXXXXX
thread 'test_mktemp::test_mktemp_tmpdir_one_arg' panicked at 'assertion failed: self.success', tests\common\util.rs:86:9


failures:
    test_ls::test_ls_human
    test_mktemp::test_mktemp_directory_tmpdir
    test_mktemp::test_mktemp_make_temp_dir
    test_mktemp::test_mktemp_mktemp
    test_mktemp::test_mktemp_mktemp_t
    test_mktemp::test_mktemp_suffix
    test_mktemp::test_mktemp_tmpdir_one_arg
```

**Comment by chadbrewbaker** [comment]
First test fails from truncate not existing on Powershell. Fixed in https://github.com/uutils/coreutils/pull/1748

**Comment by tertsdiepraam** [comment]
@chadbrewbaker Are you still having these issues or have they been resolved?

**Comment by cakebaker** [comment]
Closing this ticket as there has been no activity in more than two years. Please reopen if the issue still exists.
