### ISSUE TITLE
date --set is failing in freebsd

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1882]
```

---- test_date::test_date_set_valid_2 stdout ----
current_directory_resolved: 
run: /tmp/cirrus-ci-build/target/debug/coreutils date --set Sat 20 Mar 2021 14:53:01 AWST
thread 'test_date::test_date_set_valid_2' panicked at 'assertion failed: self.success', tests/common/util.rs:86:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_date::test_date_set_valid_3 stdout ----
current_directory_resolved: 
run: /tmp/cirrus-ci-build/target/debug/coreutils date --set Sat 20 Mar 2021 14:53:01
thread 'test_date::test_date_set_valid_3' panicked at 'assertion failed: self.success', tests/common/util.rs:86:9

---- test_date::test_date_set_valid_4 stdout ----
current_directory_resolved: 
run: /tmp/cirrus-ci-build/target/debug/coreutils date --set 2020-03-11 21:45:00
thread 'test_date::test_date_set_valid_4' panicked at 'assertion failed: self.success', tests/common/util.rs:86:9

```
https://github.com/uutils/coreutils/pull/1852/checks?check_run_id=2161834207

Caused by https://github.com/uutils/coreutils/pull/1798

@marcosatti  could you please have a look?

**Comment by marcosatti** [comment]
@sylvestre Those are expected to fail at the moment - that was what PR #1846 added in. Do you want me to change it to assert a failure for now instead? 

GNU handles those dates correctly under my system.

**Comment by sylvestre** [comment]
yeah, for these platforms too :)
thanks

**Comment by tertsdiepraam** [comment]
These tests are still set to expect failure. So still needs to be fixed.
