### ISSUE TITLE
`test -O foo` is failing

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2337]
GNU:
```
       -O FILE
              FILE exists and is owned by the effective user ID
```

```
$ RUST_BACKTRACE=1 ./target/debug/test -O foo
thread 'main' panicked at 'explicit panic', src/uu/test/src/test.rs:109:22
stack backtrace:
   0: std::panicking::begin_panic
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: uu_test::eval
             at ./src/uu/test/src/test.rs:109:22
   2: uu_test::uumain::{{closure}}
             at ./src/uu/test/src/test.rs:20:51
   3: core::result::Result<T,E>::and_then
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:704:22
   4: uu_test::uumain
             at ./src/uu/test/src/test.rs:20:18
   5: test::main
             at ./src/uu/test/src/main.rs:1:1
   6: core::ops::function::FnOnce::call_once
             at /home/sylvestre/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sylvestre** [comment]
@drocco007 Do you want to give it a try ? :)

**Comment by drocco007** [comment]
sure! I'll take a look :)
