### ISSUE TITLE
3M occurrences of the same error message in the GNU CI testsuite

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3268]
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`
is appearing a lot in the logs of the GNU testsuite.

Besides making the log slower, it makes the store log fails, this is why I wrote this workaround:
https://github.com/uutils/coreutils/pull/3267

According to https://github.com/uutils/coreutils/actions/workflows/GnuTests.yml?query=branch%3Amain the first failure happened with
https://github.com/uutils/coreutils/pull/3205

and, before the error, the logs have 
```

2022-03-18T00:40:19.6131418Z FAIL tests/misc/sort-stale-thread-mem.sh (exit status: 3)
2022-03-18T00:40:19.6131489Z 
2022-03-18T00:40:19.6131570Z FAIL: tests/split/filter
2022-03-18T00:40:19.6131692Z ========================
2022-03-18T00:40:19.6131697Z 
2022-03-18T00:40:19.6131809Z xz (XZ Utils) 5.2.4
2022-03-18T00:40:19.6131920Z liblzma 5.2.4
2022-03-18T00:40:19.6132360Z thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/uu/split/src/split.rs:1025:67
2022-03-18T00:40:19.6132434Z stack backtrace:
2022-03-18T00:40:19.6132550Z    0: rust_begin_unwind
2022-03-18T00:40:19.6132763Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/std/src/panicking.rs:584:5
2022-03-18T00:40:19.6132931Z    1: core::panicking::panic_fmt
2022-03-18T00:40:19.6133156Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/core/src/panicking.rs:143:14
2022-03-18T00:40:19.6133304Z    2: core::panicking::panic_bounds_check
2022-03-18T00:40:19.6133463Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/core/src/panicking.rs:84:5
2022-03-18T00:40:19.6133639Z    3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
2022-03-18T00:40:19.6133862Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/core/src/slice/index.rs:240:14
2022-03-18T00:40:19.6134050Z    4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
2022-03-18T00:40:19.6134251Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/core/src/slice/index.rs:29:9
2022-03-18T00:40:19.6134426Z    5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
2022-03-18T00:40:19.6134583Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/alloc/src/vec/mod.rs:2543:9
2022-03-18T00:40:19.6134773Z    6: uu_split::split_into_n_chunks_by_byte
2022-03-18T00:40:19.6134982Z              at /home/runner/work/coreutils/coreutils/uutils/src/uu/split/src/split.rs:1025:67
2022-03-18T00:40:19.6135094Z    7: uu_split::split
2022-03-18T00:40:19.6135292Z              at /home/runner/work/coreutils/coreutils/uutils/src/uu/split/src/split.rs:1220:13
2022-03-18T00:40:19.6135376Z    8: uu_split::uumain::uumain
2022-03-18T00:40:19.6135570Z              at /home/runner/work/coreutils/coreutils/uutils/src/uu/split/src/split.rs:59:25
2022-03-18T00:40:19.6135683Z    9: uu_split::uumain
2022-03-18T00:40:19.6135877Z              at /home/runner/work/coreutils/coreutils/uutils/src/uu/split/src/split.rs:55:1
2022-03-18T00:40:19.6135984Z   10: split::main
2022-03-18T00:40:19.6136216Z              at /home/runner/work/coreutils/coreutils/uutils/src/uucore/src/lib/lib.rs:90:24
2022-03-18T00:40:19.6136321Z   11: core::ops::function::FnOnce::call_once
2022-03-18T00:40:19.6136527Z              at /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/library/core/src/ops/function.rs:227:5
2022-03-18T00:40:19.6136734Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-03-18T00:40:19.6137110Z ./tests/split/filter.sh: line 44: 310163 Aborted                 (core dumped) split -e -n 10 --filter='xz > $FILE.xz' /dev/null
2022-03-18T00:40:19.6137249Z split: invalid number of chunks: 1/2
2022-03-18T00:40:19.6137387Z split: input/output error: Broken pipe
2022-03-18T00:40:19.6137512Z head: error reading standard input: Input/output error
2022-03-18T00:40:19.6137769Z truncate: cannot open '' for writing: No such file or directory
2022-03-18T00:40:19.6137885Z split: Broken pipe
2022-03-18T00:40:19.6138033Z split: Broken pipe
2022-03-18T00:40:19.6138171Z split: input/output error: Broken pipe

```

@jfinkels any idea?

I will probably revert
https://github.com/uutils/coreutils/pull/3205

**Comment by jfinkels** [comment]
Oh no! Sorry to have caused an issue here. :grimacing: I'm not sure what the problem is, but I can investigate.

**Comment by sylvestre** [comment]
no worries :)

**Comment by jfinkels** [comment]
It looks like the test case that causes the error messages
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
is the `buf = 1000000` iteration of this loop in `tests/split/filter.sh`:
```sh
for buf in 1000 1000000; do
  returns_ 124 timeout .5 sh -c \
    "yes | split --filter='head -c1 >/dev/null' -b $buf" || fail=1
done
```
but I don't recognize that error and I don't know why it would be happening. It doesn't seem to happen when I run just the command
```sh
timeout .5 sh -c "yes | ./target/release/split --filter='head -c1 >/dev/null' -b 1000000"
```

**Comment by anastygnome** [comment]
> It looks like the test case that causes the error messages
> 
> ```
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
> ```
> 
> is the `buf = 1000000` iteration of this loop in `tests/split/filter.sh`:
> 
> ```shell
> for buf in 1000 1000000; do
>   returns_ 124 timeout .5 sh -c \
>     "yes | split --filter='head -c1 >/dev/null' -b $buf" || fail=1
> done
> ```
> 
> but I don't recognize that error and I don't know why it would be happening. It doesn't seem to happen when I run just the command
> 
> ```shell
> timeout .5 sh -c "yes | ./target/release/split --filter='head -c1 >/dev/null' -b 1000000"
> ```

This maybe due to the repository not existing when the command is ran ? 

I am unfamiliar with this but is there a second terminal/ script / task that may remove the directory at that moment of the execution ?

**Comment by jfinkels** [comment]
I recreated the pull request #3281 so that it will be easier for someone to help diagnose the issue here.

**Comment by sylvestre** [comment]
Fixed now with the backout :)
