### ISSUE TITLE
Freebsd: some tests are failing

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3778]
Follow up of https://github.com/uutils/coreutils/issues/3733

```

2022-08-05T06:49:49.6230420Z failures:
2022-08-05T06:49:49.6230820Z 
2022-08-05T06:49:49.6409200Z ---- test_cp::test_copy_through_dangling_symlink_no_dereference_permissions stdout ----
2022-08-05T06:49:49.6409810Z current_directory_resolved: 
2022-08-05T06:49:49.6410590Z symlink: /tmp/.tmpXoQlGW/no-such-file,/tmp/.tmpXoQlGW/dangle
2022-08-05T06:49:49.6411320Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils cp -P -p dangle d2
2022-08-05T06:49:49.6412000Z thread 'test_cp::test_copy_through_dangling_symlink_no_dereference_permissions' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6412330Z stdout = 
2022-08-05T06:49:49.6412560Z  stderr = cp: No such file or directory (os error 2)
2022-08-05T06:49:49.6413450Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6413590Z 
2022-08-05T06:49:49.6421770Z ---- test_df::test_file_column_width_if_filename_contains_unicode_chars stdout ----
2022-08-05T06:49:49.6422140Z current_directory_resolved: 
2022-08-05T06:49:49.6422550Z touch: /tmp/.tmp6weDfN/äöü.txt
2022-08-05T06:49:49.6423010Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output=file,target äöü.txt
2022-08-05T06:49:49.6423660Z thread 'test_df::test_file_column_width_if_filename_contains_unicode_chars' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6423980Z stdout = 
2022-08-05T06:49:49.6424190Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6424500Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6424640Z 
2022-08-05T06:49:49.6424910Z ---- test_df::test_nonexistent_file stdout ----
2022-08-05T06:49:49.6425170Z current_directory_resolved: 
2022-08-05T06:49:49.6425600Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df does-not-exist
2022-08-05T06:49:49.6425910Z current_directory_resolved: 
2022-08-05T06:49:49.6426360Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output=file does-not-exist .
2022-08-05T06:49:49.6426930Z thread 'test_df::test_nonexistent_file' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6427130Z 
2022-08-05T06:49:49.6427340Z [1mDiff[0m [31m< left[0m / [32mright >[0m :
2022-08-05T06:49:49.6427690Z  df: does-not-exist: No such file or directory
2022-08-05T06:49:49.6428020Z [31m<df: no file systems processed[0m
2022-08-05T06:49:49.6428170Z 
2022-08-05T06:49:49.6428340Z ', tests/common/util.rs:328:9
2022-08-05T06:49:49.6428480Z 
2022-08-05T06:49:49.6428770Z ---- test_df::test_output_file_specific_files stdout ----
2022-08-05T06:49:49.6429030Z current_directory_resolved: 
2022-08-05T06:49:49.6429240Z touch: /tmp/.tmpWoDvyQ/a
2022-08-05T06:49:49.6429460Z touch: /tmp/.tmpWoDvyQ/b
2022-08-05T06:49:49.6429670Z touch: /tmp/.tmpWoDvyQ/c
2022-08-05T06:49:49.6430100Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output=file a b c
2022-08-05T06:49:49.6430640Z thread 'test_df::test_output_file_specific_files' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6431270Z stdout = 
2022-08-05T06:49:49.6431540Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6431780Z df: no file systems processed
2022-08-05T06:49:49.6432000Z df: no file systems processed
2022-08-05T06:49:49.6432320Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6432460Z 
2022-08-05T06:49:49.6432730Z ---- test_df::test_output_mp_repeat stdout ----
2022-08-05T06:49:49.6432990Z current_directory_resolved: 
2022-08-05T06:49:49.6433280Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df / /
2022-08-05T06:49:49.6433790Z thread 'test_df::test_output_mp_repeat' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6434070Z stdout = 
2022-08-05T06:49:49.6434340Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6434790Z df: no file systems processed
2022-08-05T06:49:49.6435140Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6435260Z 
2022-08-05T06:49:49.6435780Z ---- test_df::test_output_option_without_equals_sign stdout ----
2022-08-05T06:49:49.6436100Z current_directory_resolved: 
2022-08-05T06:49:49.6436540Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output .
2022-08-05T06:49:49.6437100Z thread 'test_df::test_output_option_without_equals_sign' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6437390Z stdout = 
2022-08-05T06:49:49.6437590Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6437910Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6438050Z 
2022-08-05T06:49:49.6438520Z ---- test_df::test_total_label_in_correct_column stdout ----
2022-08-05T06:49:49.6438800Z current_directory_resolved: 
2022-08-05T06:49:49.6439270Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output=source --total .
2022-08-05T06:49:49.6848030Z thread 'test_df::test_total_label_in_correct_column' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6848330Z stdout = 
2022-08-05T06:49:49.6848550Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6848900Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6849040Z 
2022-08-05T06:49:49.6849360Z ---- test_df::test_type_option_with_file stdout ----
2022-08-05T06:49:49.6849620Z current_directory_resolved: 
2022-08-05T06:49:49.6850060Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils df --output=fstype .
2022-08-05T06:49:49.6850590Z thread 'test_df::test_type_option_with_file' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6850880Z stdout = 
2022-08-05T06:49:49.6851090Z  stderr = df: no file systems processed
2022-08-05T06:49:49.6851400Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6851540Z 
2022-08-05T06:49:49.6851810Z ---- test_ls::test_ls_allocation_size stdout ----
2022-08-05T06:49:49.6852050Z current_directory_resolved: 
2022-08-05T06:49:49.6852390Z mkdir: /tmp/.tmpJEtd9H/some-dir1
2022-08-05T06:49:49.6852730Z touch: /tmp/.tmpJEtd9H/some-dir1/empty-file
2022-08-05T06:49:49.6853220Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils truncate -s 4M some-dir1/file-with-holes
2022-08-05T06:49:49.6853830Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils dd --if=/dev/zero --of=some-dir1/zero-file bs=1024 count=4096
2022-08-05T06:49:49.6854430Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils dd --if=/dev/zero --of=irregular-file bs=1 count=777
2022-08-05T06:49:49.6854990Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -l --block-size=512 irregular-file
2022-08-05T06:49:49.6855540Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -s1 some-dir1
2022-08-05T06:49:49.6856080Z thread 'test_ls::test_ls_allocation_size' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6856290Z 
2022-08-05T06:49:49.6856490Z [1mDiff[0m [31m< left[0m / [32mright >[0m :
2022-08-05T06:49:49.6856860Z [31m<total 4[0m[1;48;5;52;31m1[0m[31m9[0m[1;48;5;52;31m2[0m
2022-08-05T06:49:49.6857220Z [32m>total 4[0m[1;48;5;22;32m0[0m[32m9[0m[1;48;5;22;32m6[0m
2022-08-05T06:49:49.6857500Z     0 empty-file
2022-08-05T06:49:49.6858220Z [31m<  64 file-with-holes[0m
2022-08-05T06:49:49.6858590Z [31m<4128 zero-file[0m
2022-08-05T06:49:49.6858870Z [32m>   0 file-with-holes[0m
2022-08-05T06:49:49.6859140Z [32m>4096 zero-file[0m
2022-08-05T06:49:49.6859330Z  
2022-08-05T06:49:49.6859420Z 
2022-08-05T06:49:49.6859590Z ', tests/common/util.rs:235:9
2022-08-05T06:49:49.6859730Z 
2022-08-05T06:49:49.6859990Z ---- test_ls::test_ls_io_errors stdout ----
2022-08-05T06:49:49.6860240Z current_directory_resolved: 
2022-08-05T06:49:49.6860550Z mkdir: /tmp/.tmpVG3z4I/some-dir1
2022-08-05T06:49:49.6860860Z mkdir: /tmp/.tmpVG3z4I/some-dir2
2022-08-05T06:49:49.6861250Z symlink: /tmp/.tmpVG3z4I/does_not_exist,/tmp/.tmpVG3z4I/some-dir2/dangle
2022-08-05T06:49:49.6861630Z mkdir: /tmp/.tmpVG3z4I/some-dir3
2022-08-05T06:49:49.6861950Z mkdir: /tmp/.tmpVG3z4I/some-dir3/some-dir4
2022-08-05T06:49:49.6862270Z mkdir: /tmp/.tmpVG3z4I/some-dir4
2022-08-05T06:49:49.6862700Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils chmod 000 some-dir1
2022-08-05T06:49:49.6863180Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -1 some-dir1
2022-08-05T06:49:49.6863650Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -Li some-dir2
2022-08-05T06:49:49.6864160Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils chmod 000 some-dir3/some-dir4
2022-08-05T06:49:49.6864650Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -laR some-dir3
2022-08-05T06:49:49.6865120Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -iRL some-dir2
2022-08-05T06:49:49.6865510Z touch: /tmp/.tmpVG3z4I/some-dir4/bad-fd.txt
2022-08-05T06:49:49.6865860Z open: /tmp/.tmpVG3z4I/some-dir4/bad-fd.txt
2022-08-05T06:49:49.6866580Z [/Users/runner/work/coreutils/coreutils/tests/by-util/test_ls.rs:419] fd1 = 4
2022-08-05T06:49:49.6867050Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils ls -alR /dev/fd/5
2022-08-05T06:49:49.6867570Z thread 'test_ls::test_ls_io_errors' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6867840Z stdout = 
2022-08-05T06:49:49.6868190Z  stderr = ls: cannot access '/dev/fd/5': No such file or directory
2022-08-05T06:49:49.6868700Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6868830Z 
2022-08-05T06:49:49.6869120Z ---- test_stat::test_stdin_pipe_fifo1 stdout ----
2022-08-05T06:49:49.6869380Z current_directory_resolved: 
2022-08-05T06:49:49.6869670Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils stat -
2022-08-05T06:49:49.6870150Z thread 'test_stat::test_stdin_pipe_fifo1' panicked at ''  File: -
2022-08-05T06:49:49.6870460Z   Size: 0         	Blocks: 0          IO Block: 4096   character special file
2022-08-05T06:49:49.6870760Z Device: 7100ff00h/1895890688d	Inode: 11          Links: 1     Device type: 0,b
2022-08-05T06:49:49.6871180Z Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/   wheel)
2022-08-05T06:49:49.6871530Z Access: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6871850Z Modify: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6872160Z Change: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6872360Z  Birth: -
2022-08-05T06:49:49.6872670Z ' does not contain 'fifo'', tests/common/util.rs:410:9
2022-08-05T06:49:49.6872840Z 
2022-08-05T06:49:49.6873110Z ---- test_stat::test_stdin_redirect stdout ----
2022-08-05T06:49:49.6873360Z current_directory_resolved: 
2022-08-05T06:49:49.6873590Z touch: /tmp/.tmpcPbzaB/f
2022-08-05T06:49:49.6873870Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils stat -
2022-08-05T06:49:49.6874330Z thread 'test_stat::test_stdin_redirect' panicked at ''  File: -
2022-08-05T06:49:49.6874650Z   Size: 0         	Blocks: 0          IO Block: 4096   character special file
2022-08-05T06:49:49.6874960Z Device: 7100ff00h/1895890688d	Inode: 11          Links: 1     Device type: 0,b
2022-08-05T06:49:49.6875370Z Access: (0666/crw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/   wheel)
2022-08-05T06:49:49.6875960Z Access: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6876360Z Modify: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6876650Z Change: 2022-08-05 06:32:06.975010000 +0000
2022-08-05T06:49:49.6876860Z  Birth: -
2022-08-05T06:49:49.6877210Z ' does not contain 'regular empty file'', tests/common/util.rs:410:9
2022-08-05T06:49:49.6877390Z 
2022-08-05T06:49:49.6877700Z ---- test_tail::test_follow_inotify_only_regular stdout ----
2022-08-05T06:49:49.6877970Z current_directory_resolved: 
2022-08-05T06:49:49.6878380Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail -f /dev/null
2022-08-05T06:49:49.6878930Z thread 'test_tail::test_follow_inotify_only_regular' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6880070Z   left: `"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Generic(\"Operation not supported by device (os error 19)\"), paths: [] }', src/uu/tail/src/tail.rs:1646:56\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"`,
2022-08-05T06:49:49.6880780Z  right: `""`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2326:5
2022-08-05T06:49:49.6881200Z 
2022-08-05T06:49:49.6881520Z ---- test_tail::test_follow_name_move1 stdout ----
2022-08-05T06:49:49.6881780Z current_directory_resolved: 
2022-08-05T06:49:49.6882050Z open: /tmp/.tmp3F6rTu/follow_name_short.expected
2022-08-05T06:49:49.6882530Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail --follow=name follow_name.txt
2022-08-05T06:49:49.6883190Z rename: "/tmp/.tmp3F6rTu/follow_name.txt" "/tmp/.tmp3F6rTu/backup"
2022-08-05T06:49:49.6883990Z thread 'test_tail::test_follow_name_move1' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6884600Z   left: `""`,
2022-08-05T06:49:49.6885150Z  right: `"tail: follow_name.txt: No such file or directory\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2067:9
2022-08-05T06:49:49.6885410Z 
2022-08-05T06:49:49.6885720Z ---- test_tail::test_follow_name_move2 stdout ----
2022-08-05T06:49:49.6885980Z current_directory_resolved: 
2022-08-05T06:49:49.6886220Z write(truncate): /tmp/.tmpn8727v/file1
2022-08-05T06:49:49.6886450Z write(truncate): /tmp/.tmpn8727v/file2
2022-08-05T06:49:49.6886920Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail --follow=name file1 file2
2022-08-05T06:49:49.6887260Z rename: "/tmp/.tmpn8727v/file1" "/tmp/.tmpn8727v/file2"
2022-08-05T06:49:49.6887520Z write(append): /tmp/.tmpn8727v/file2
2022-08-05T06:49:49.6887760Z write(append): /tmp/.tmpn8727v/file1
2022-08-05T06:49:49.6887960Z out:
2022-08-05T06:49:49.6888130Z ==> file1 <==
2022-08-05T06:49:49.6888310Z file1_content
2022-08-05T06:49:49.6888420Z 
2022-08-05T06:49:49.6888490Z ==> file2 <==
2022-08-05T06:49:49.6888680Z file2_content
2022-08-05T06:49:49.6888790Z 
2022-08-05T06:49:49.6888850Z err:
2022-08-05T06:49:49.6889050Z tail: file2: No such file or directory
2022-08-05T06:49:49.6889190Z 
2022-08-05T06:49:49.6889560Z thread 'test_tail::test_follow_name_move2' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6889920Z   left: `"==> file1 <==\nfile1_content\n\n==> file2 <==\nfile2_content\n"`,
2022-08-05T06:49:49.6890650Z  right: `"==> file1 <==\nfile1_content\n\n==> file2 <==\nfile2_content\nfile1_content\nmore_file2_content\n\n==> file1 <==\nmore_file1_content\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2139:9
2022-08-05T06:49:49.6890990Z 
2022-08-05T06:49:49.6891280Z ---- test_tail::test_follow_name_move_create1 stdout ----
2022-08-05T06:49:49.6891540Z current_directory_resolved: 
2022-08-05T06:49:49.6891800Z open: /tmp/.tmpFBQMju/follow_name_short.expected
2022-08-05T06:49:49.6892290Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail --follow=name follow_name.txt
2022-08-05T06:49:49.6892660Z rename: "/tmp/.tmpFBQMju/follow_name.txt" "/tmp/.tmpFBQMju/backup"
2022-08-05T06:49:49.6892980Z copy: "/tmp/.tmpFBQMju/backup" "/tmp/.tmpFBQMju/follow_name.txt"
2022-08-05T06:49:49.6893770Z thread 'test_tail::test_follow_name_move_create1' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6894110Z   left: `""`,
2022-08-05T06:49:49.6894620Z  right: `"tail: follow_name.txt: No such file or directory\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:1956:5
2022-08-05T06:49:49.6894880Z 
2022-08-05T06:49:49.6895180Z ---- test_tail::test_follow_name_move_create2 stdout ----
2022-08-05T06:49:49.6895450Z current_directory_resolved: 
2022-08-05T06:49:49.6895670Z touch: /tmp/.tmpCklKO1/1
2022-08-05T06:49:49.6895880Z touch: /tmp/.tmpCklKO1/2
2022-08-05T06:49:49.6896090Z touch: /tmp/.tmpCklKO1/3
2022-08-05T06:49:49.6896290Z touch: /tmp/.tmpCklKO1/4
2022-08-05T06:49:49.6896490Z touch: /tmp/.tmpCklKO1/5
2022-08-05T06:49:49.6896710Z touch: /tmp/.tmpCklKO1/6
2022-08-05T06:49:49.6896970Z touch: /tmp/.tmpCklKO1/7
2022-08-05T06:49:49.6897180Z touch: /tmp/.tmpCklKO1/8
2022-08-05T06:49:49.6897370Z touch: /tmp/.tmpCklKO1/9
2022-08-05T06:49:49.6897900Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail -s.1 --max-unchanged-stats=1 -q -F 1 2 3 4 5 6 7 8 9
2022-08-05T06:49:49.6898240Z write(truncate): /tmp/.tmpCklKO1/9
2022-08-05T06:49:49.6898500Z rename: "/tmp/.tmpCklKO1/1" "/tmp/.tmpCklKO1/f"
2022-08-05T06:49:49.6898750Z write(truncate): /tmp/.tmpCklKO1/1
2022-08-05T06:49:49.6899240Z thread 'test_tail::test_follow_name_move_create2' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6899540Z   left: `""`,
2022-08-05T06:49:49.6900140Z  right: `"tail: '1' has become inaccessible: No such file or directory\ntail: '1' has appeared;  following new file\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2005:9
2022-08-05T06:49:49.6900450Z 
2022-08-05T06:49:49.6901300Z ---- test_tail::test_follow_name_move_retry2 stdout ----
2022-08-05T06:49:49.6901570Z current_directory_resolved: 
2022-08-05T06:49:49.6901800Z touch: /tmp/.tmpT2SD9Q/a
2022-08-05T06:49:49.6902000Z touch: /tmp/.tmpT2SD9Q/b
2022-08-05T06:49:49.6902490Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail -s.1 --max-unchanged-stats=1 -F a b
2022-08-05T06:49:49.6902820Z write(truncate): /tmp/.tmpT2SD9Q/a
2022-08-05T06:49:49.6903070Z rename: "/tmp/.tmpT2SD9Q/a" "/tmp/.tmpT2SD9Q/b"
2022-08-05T06:49:49.6903320Z write(truncate): /tmp/.tmpT2SD9Q/a
2022-08-05T06:49:49.6903560Z write(append): /tmp/.tmpT2SD9Q/b
2022-08-05T06:49:49.6903790Z write(append): /tmp/.tmpT2SD9Q/a
2022-08-05T06:49:49.6904290Z thread 'test_tail::test_follow_name_move_retry2' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6904610Z   left: `"==> a <==\n\n==> b <==\n\n==> a <==\nx\n"`,
2022-08-05T06:49:49.6905220Z  right: `"==> a <==\n\n==> b <==\n\n==> a <==\nx\n\n==> b <==\nx\n\n==> a <==\nx2\n\n==> b <==\ny\n\n==> a <==\nz\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2286:9
2022-08-05T06:49:49.6905520Z 
2022-08-05T06:49:49.6906050Z ---- test_tail::test_follow_name_move_retry1 stdout ----
2022-08-05T06:49:49.6906320Z current_directory_resolved: 
2022-08-05T06:49:49.6906560Z touch: /tmp/.tmpCC6DB2/follow_name.txt
2022-08-05T06:49:49.6907080Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail --follow=name --retry follow_name.txt --use-polling
2022-08-05T06:49:49.6907440Z write(append): /tmp/.tmpCC6DB2/follow_name.txt
2022-08-05T06:49:49.6907740Z rename: "/tmp/.tmpCC6DB2/follow_name.txt" "/tmp/.tmpCC6DB2/backup"
2022-08-05T06:49:49.6908020Z write(truncate): /tmp/.tmpCC6DB2/backup
2022-08-05T06:49:49.6908310Z rename: "/tmp/.tmpCC6DB2/backup" "/tmp/.tmpCC6DB2/follow_name.txt"
2022-08-05T06:49:49.6908830Z thread 'test_tail::test_follow_name_move_retry1' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6909120Z   left: `"tailed\n"`,
2022-08-05T06:49:49.6909590Z  right: `"tailed\nnew content\n"`', /Users/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:2199:9
2022-08-05T06:49:49.6909820Z 
2022-08-05T06:49:49.6910100Z ---- test_tail::test_stdin_redirect_dir stdout ----
2022-08-05T06:49:49.6910610Z current_directory_resolved: 
2022-08-05T06:49:49.6910890Z mkdir: /tmp/.tmpuNHxli/dir
2022-08-05T06:49:49.6911160Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils tail
2022-08-05T06:49:49.6911730Z thread 'test_tail::test_stdin_redirect_dir' panicked at 'assertion failed: `(left == right)`
2022-08-05T06:49:49.6911950Z 
2022-08-05T06:49:49.6912150Z [1mDiff[0m [31m< left[0m / [32mright >[0m :
2022-08-05T06:49:49.6912810Z [31m<thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', src/uu/tail/src/tail.rs:1440:49[0m
2022-08-05T06:49:49.6913370Z [31m<note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace[0m
2022-08-05T06:49:49.6913810Z [32m>tail: error reading 'standard input': Is a directory[0m
2022-08-05T06:49:49.6913990Z 
2022-08-05T06:49:49.6914160Z ', tests/common/util.rs:328:9
2022-08-05T06:49:49.6914290Z 
2022-08-05T06:49:49.6914610Z ---- test_touch::test_touch_changes_time_of_file_in_stdout stdout ----
2022-08-05T06:49:49.6914900Z current_directory_resolved: 
2022-08-05T06:49:49.6915170Z touch: /tmp/.tmpb0zosb/test_touch_changes_time_of_file_in_stdout
2022-08-05T06:49:49.6915500Z run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils touch -
2022-08-05T06:49:49.6916060Z thread 'test_touch::test_touch_changes_time_of_file_in_stdout' panicked at 'Command was expected to succeed.
2022-08-05T06:49:49.6916350Z stdout = 
2022-08-05T06:49:49.6916700Z  stderr = touch: setting times of '/dev/stdout': Permission denied
2022-08-05T06:49:49.6917050Z ', tests/common/util.rs:176:9
2022-08-05T06:49:49.6917180Z 
2022-08-05T06:49:49.6917240Z 
2022-08-05T06:49:49.6917320Z failures:
2022-08-05T06:49:49.6917600Z     test_cp::test_copy_through_dangling_symlink_no_dereference_permissions
2022-08-05T06:49:49.6918190Z     test_df::test_file_column_width_if_filename_contains_unicode_chars
2022-08-05T06:49:49.6918470Z     test_df::test_nonexistent_file
2022-08-05T06:49:49.6918720Z     test_df::test_output_file_specific_files
2022-08-05T06:49:49.6918970Z     test_df::test_output_mp_repeat
2022-08-05T06:49:49.6919230Z     test_df::test_output_option_without_equals_sign
2022-08-05T06:49:49.6919510Z     test_df::test_total_label_in_correct_column
2022-08-05T06:49:49.6919760Z     test_df::test_type_option_with_file
2022-08-05T06:49:49.6920000Z     test_ls::test_ls_allocation_size
2022-08-05T06:49:49.6920220Z     test_ls::test_ls_io_errors
2022-08-05T06:49:49.6920450Z     test_stat::test_stdin_pipe_fifo1
2022-08-05T06:49:49.6920890Z     test_stat::test_stdin_redirect
2022-08-05T06:49:49.6921170Z     test_tail::test_follow_inotify_only_regular
2022-08-05T06:49:49.6921420Z     test_tail::test_follow_name_move1
2022-08-05T06:49:49.6921640Z     test_tail::test_follow_name_move2
2022-08-05T06:49:49.6921900Z     test_tail::test_follow_name_move_create1
2022-08-05T06:49:49.6922160Z     test_tail::test_follow_name_move_create2
2022-08-05T06:49:49.6922410Z     test_tail::test_follow_name_move_retry1
2022-08-05T06:49:49.6922670Z     test_tail::test_follow_name_move_retry2
2022-08-05T06:49:49.6922910Z     test_tail::test_stdin_redirect_dir
2022-08-05T06:49:49.6923170Z     test_touch::test_touch_changes_time_of_file_in_stdout
2022-08-05T06:49:49.6923340Z 
2022-08-05T06:49:49.6923530Z test result: FAILED. 2116 passed; 21 failed; 39 ignored; 0 measured; 0 filtered out; finished in 113.58s
```

**Comment by sylvestre** [comment]
Reopened as the tests are ignored, not fixed

**Comment by naoNao89** [comment]
The kqueue issue is already fixed (commit 79c0624, 2024)

The code now watches parent directories on BSD/macOS, properly handling file rotation.

Repro showing it works:
```bash
cd /tmp
echo "original" > test.txt
tail --follow=name test.txt &
sleep 1
mv test.txt test.bak
echo "new" > test.txt
sleep 2
# Output: Shows both "original" and "new" ✓
```
Why tests were disabled:
1. Expected Linux inotify error messages ("No such file")
2. kqueue parent watching has **different valid behavior** (no errors during rename)
3. Missing test file setup

**Comment by xtqqczze** [comment]
There are still about 148 failing tests in the in FreeBSD tests logs: https://github.com/uutils/coreutils/actions/runs/35002278602/job/104493321799?pr=14582.
