### ISSUE TITLE
`test_month_stable` is failing intermittently 

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4218]
```


---- test_sort::test_month_stable stdout ----
current_directory_resolved: 
run: D:\a\coreutils\coreutils\target\debug\coreutils.exe sort month_stable.txt -Ms
---- test_sort::test_month_stable stderr ----
thread 'main' panicked at 'Command was expected to succeed.
stdout = N/A Ut enim ad minim veniam, quis
 asdf
Jan Lorem ipsum dolor sit amet
mar laboris nisi ut aliquip ex ea
May sed do eiusmod tempor incididunt
JUN nostrud exercitation ullamco
Jul 2 these three lines
Jul 1 should remain 2,1,3
Jul 3 if --stable is provided
Oct ut labore et dolore magna aliqua
Dec consectetur adipiscing elit

 stderr = 
thread 'main' has overflowed its stack
', tests\common\util.rs:177:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_sort::test_month_stable

```
Run:
https://github.com/uutils/coreutils/actions/runs/3627560164/jobs/6117569370

**Comment by Joining7943** [comment]
I've also seen `test_sort::test_human_numeric_whitespace` failing on windows because of the same reason `has overflowed its stack`

```
---- test_sort::test_human_numeric_whitespace stdout ----
current_directory_resolved: 
run: D:\a\coreutils\coreutils\target\debug\coreutils.exe sort human-numeric-whitespace.txt -h
open: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpIRiCrq\human-numeric-whitespace.expected
current_directory_resolved: 
run: D:\a\coreutils\coreutils\target\debug\coreutils.exe sort human-numeric-whitespace.txt --debug -h
open: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpEuQ5pw\human-numeric-whitespace.expected.debug
current_directory_resolved: 
run: D:\a\coreutils\coreutils\target\debug\coreutils.exe sort human-numeric-whitespace.txt --human-numeric-sort
---- test_sort::test_human_numeric_whitespace stderr ----
thread 'main' panicked at 'Command was expected to succeed.
stdout = 






456K
4568K
			456M
              6.2G

 stderr = 
thread 'main' has overflowed its stack
', tests\common\util.rs:179:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\std\src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\core\src/panicking.rs:64:14
   2: tests::common::util::CmdResult::success
             at .\tests\common\util.rs:179:9
   3: tests::common::util::UCommand::succeeds
             at .\tests\common\util.rs:1223:9
   4: tests::test_sort::test_helper
             at .\tests\by-util\test_sort.rs:14:9
   5: tests::test_sort::test_human_numeric_whitespace
             at .\tests\by-util\test_sort.rs:139:5
   6: tests::test_sort::test_human_numeric_whitespace::{{closure}}
             at .\tests\by-util\test_sort.rs:138:36
   7: core::ops::function::FnOnce::call_once
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d\library\core\src\ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\core\src\ops/function.rs:250:5
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\core\src\ops/function.rs:250:5
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\alloc\src/boxed.rs:1988:9
  11: test::run_test_in_spawned_subprocess
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\test\src/lib.rs:793:27
  12: test::test_main_static_abort
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library\test\src/lib.rs:186:9
  13: tests::main
             at .\tests\tests.rs:1:1
  14: core::ops::function::FnOnce::call_once
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d\library\core\src\ops/function.rs:250:5
```

**Comment by sylvestre** [comment]
didn't happen for a while, closing
