### ISSUE TITLE
test_touch in Ubuntu code coverage recently started to fail (probably because of dailylight saving change)

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4584]
```

failures:
    test_touch::test_touch_leap_second
    test_touch::test_touch_set_both
    test_touch::test_touch_set_cymdhm_time
    test_touch::test_touch_set_cymdhms_time
    test_touch::test_touch_set_date
    test_touch::test_touch_set_date2

```

```

---- test_touch::test_touch_leap_second stdout ----
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils touch -t 197001010000.60 test_touch_leap_sec
---- test_touch::test_touch_leap_second stderr ----
thread 'main' panicked at 'Error The system's UTC offset could not be determined retrieving the OffsetDateTime::now_local', tests/by-util/test_touch.rs:55:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/panicking.rs:64:14
   2: tests::test_touch::str_to_filetime
             at ./tests/by-util/test_touch.rs:55:13
   3: tests::test_touch::test_touch_leap_second
             at ./tests/by-util/test_touch.rs:792:17
   4: tests::test_touch::test_touch_leap_second::{{closure}}
             at ./tests/by-util/test_touch.rs:782:29
   5: core::ops::function::FnOnce::call_once
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/ops/function.rs:250:5
   8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/alloc/src/boxed.rs:1988:9
   9: test::run_test_in_spawned_subprocess
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/test/src/lib.rs:793:27
  10: test::test_main_static_abort
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/test/src/lib.rs:186:9
  11: tests::main
             at ./tests/tests.rs:1:1
  12: core::ops::function::FnOnce::call_once
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
https://github.com/uutils/coreutils/actions/runs/4499044940/jobs/7916411002

**Comment by tertsdiepraam** [comment]
Instead of fixing the touch tests specifically, I'd like to come back to this: https://github.com/uutils/coreutils/pull/4446#issuecomment-1450904996

Basically, I think we should run all tests in the UTC timezone, unless otherwise specified, but we'll have to adapt some tests to make that work.

**Comment by sylvestre** [comment]
oups, thanks
