### ISSUE TITLE
`test_final_stats_unspec` fails on freebsd

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4726]
```  
  ---- test_dd::test_final_stats_unspec stdout ----
  run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils dd
  thread 'test_dd::test_final_stats_unspec' panicked at 'Stderr does not match regex:
  0+0 records in
  0+0 records out
  0 bytes copied, 0 s, 0.0 B/s
  ', tests/by-util/test_dd.rs:269:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
     2: tests::common::util::CmdResult::stderr_matches
               at ./tests/common/util.rs:702:9
     3: tests::test_dd::test_final_stats_unspec
               at ./tests/by-util/test_dd.rs:266:5
     4: tests::test_dd::test_final_stats_unspec::{{closure}}
               at ./tests/by-util/test_dd.rs:265:30
     5: core::ops::function::FnOnce::call_once
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
     6: core::ops::function::FnOnce::call_once
               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  
```

**Comment by sylvestre** [comment]
Verified fixed - test_dd::test_final_stats_unspec now passes (commit f551cc458)
