### ISSUE TITLE
Test failures (`PermissionDenied`) for 0.0.19

### ISSUE THREAD

**Issue by orhun** [uutils/coreutils#4946]
Hello, Arch Linux maintainer here! 👋🏼 

I'm getting the following test failures while building `0.0.19`:

<details>
<summary>Logs</summary>

```
failures:

---- test_mv::test_mv_move_file_into_file_with_target_arg stdout ----
thread 'test_mv::test_mv_move_file_into_file_with_target_arg' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_move_multiple_files_into_file stdout ----
thread 'test_mv::test_mv_move_multiple_files_into_file' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_numbered_if_existing_backup_existing stdout ----
thread 'test_mv::test_mv_numbered_if_existing_backup_existing' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_move_file_into_dir_with_target_arg stdout ----
thread 'test_mv::test_mv_move_file_into_dir_with_target_arg' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_move_file_between_dirs stdout ----
mkdir: /tmp/.tmpaDwH6F/test_mv_move_file_between_dirs_dir1
mkdir: /tmp/.tmpaDwH6F/test_mv_move_file_between_dirs_dir2
touch: /tmp/.tmpaDwH6F/test_mv_move_file_between_dirs_dir1/test_mv_move_file_between_dirs_file
thread 'test_mv::test_mv_move_file_between_dirs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:919:39

---- test_mv::test_mv_overwrite_dir stdout ----
thread 'test_mv::test_mv_overwrite_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_multiple_folders stdout ----
thread 'test_mv::test_mv_multiple_folders' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_move_file_into_dir stdout ----
thread 'test_mv::test_mv_move_file_into_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_numbered_if_existing_backup_nil stdout ----
thread 'test_mv::test_mv_numbered_if_existing_backup_nil' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_replace_file stdout ----
thread 'test_mv::test_mv_replace_file' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_overwrite_nonempty_dir stdout ----
thread 'test_mv::test_mv_overwrite_nonempty_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_rename_dir stdout ----
thread 'test_mv::test_mv_rename_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_multiple_files stdout ----
thread 'test_mv::test_mv_multiple_files' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_same_file_dot_dir stdout ----
thread 'test_mv::test_mv_same_file_dot_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_same_hardlink_backup_simple stdout ----
thread 'test_mv::test_mv_same_hardlink_backup_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_simple_backup stdout ----
thread 'test_mv::test_mv_simple_backup' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_strip_slashes stdout ----
thread 'test_mv::test_mv_strip_slashes' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_simple_backup_with_file_extension stdout ----
thread 'test_mv::test_mv_simple_backup_with_file_extension' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_same_hardlink stdout ----
thread 'test_mv::test_mv_same_hardlink' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_same_file_not_dot_dir stdout ----
thread 'test_mv::test_mv_same_file_not_dot_dir' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_mv::test_mv_same_file stdout ----
thread 'test_mv::test_mv_same_file' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_ls::test_ls_indicator_style stdout ----
mkdir: /tmp/.tmp6XPBX5/directory
touch: /tmp/.tmp6XPBX5/link-src
symlink: /tmp/.tmp6XPBX5/link-src,/tmp/.tmp6XPBX5/link-dest.link
is_symlink: /tmp/.tmp6XPBX5/link-dest.link
mkfifo: /tmp/.tmp6XPBX5/named-pipe.fifo
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=classify
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --ind=classify
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=file-type
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --ind=file-type
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=slash
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --ind=slash
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=always
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=yes
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=force
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --class
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --file-type
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --file
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls -p
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=none
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --ind=none
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=none
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=never
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --classify=no
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=classify
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils ls --indicator-style=file-type
thread 'test_ls::test_ls_indicator_style' panicked at 'failed to create socket: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/by-util/test_ls.rs:2077:57

---- test_mv::test_mv_no_clobber stdout ----
thread 'test_mv::test_mv_no_clobber' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_transform_without_suffix_on_input stdout ----
thread 'test_numfmt::test_transform_without_suffix_on_input' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_valid_but_forbidden_suffix stdout ----
thread 'test_numfmt::test_valid_but_forbidden_suffix' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_should_report_invalid_suffix_on_stdin stdout ----
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --from=auto
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --from=auto
thread 'test_numfmt::test_should_report_invalid_suffix_on_stdin' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_dec_offset stdout ----
thread 'test_od::test_dec_offset' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_invalid_unit_size stdout ----
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --from-unit=A
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --from-unit=0
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --from-unit=18446744073709551616
thread 'test_numfmt::test_invalid_unit_size' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_round_with_to_unit stdout ----
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to-unit=1024 --round=from-zero -- 6000 -6000 6000.0 -6000.0 6000.00 -6000.00
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to-unit=1024 --round=towards-zero -- 6000 -6000 6000.0 -6000.0 6000.00 -6000.00
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to-unit=1024 --round=up -- 6000 -6000 6000.0 -6000.0 6000.00 -6000.00
thread 'test_numfmt::test_round_with_to_unit' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_f16 stdout ----
thread 'test_od::test_f16' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_file stdout ----
thread 'test_od::test_file' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_dec stdout ----
thread 'test_od::test_dec' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_file_offset stdout ----
thread 'test_od::test_file_offset' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_f32 stdout ----
thread 'test_od::test_f32' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_filename_parsing stdout ----
thread 'test_od::test_filename_parsing' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_from_mixed stdout ----
thread 'test_od::test_from_mixed' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_f64 stdout ----
thread 'test_od::test_f64' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_big_endian stdout ----
thread 'test_od::test_big_endian' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_numfmt::test_round stdout ----
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to=si --round=from-zero -- 9001 -9001 9099 -9099
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to=si --round=towards-zero -- 9001 -9001 9099 -9099
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils numfmt --to=si --round=up -- 9001 -9001 9099 -9099
thread 'test_numfmt::test_round' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_hex32 stdout ----
thread 'test_od::test_hex32' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_hex_offset stdout ----
thread 'test_od::test_hex_offset' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_invalid_arg stdout ----
thread 'test_od::test_invalid_arg' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_max_uint stdout ----
thread 'test_od::test_max_uint' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_multibyte stdout ----
thread 'test_od::test_multibyte' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_multiple_formats stdout ----
thread 'test_od::test_multiple_formats' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_hex16 stdout ----
thread 'test_od::test_hex16' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_no_offset stdout ----
thread 'test_od::test_no_offset' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_od::test_no_file stdout ----
thread 'test_od::test_no_file' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1134:76

---- test_factor::test_parallel stdout ----
touch: /tmp/.tmpEAFAow/output
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils factor
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils factor
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils factor
run: /build/uutils-coreutils/src/coreutils-0.0.19/target/release/coreutils factor
thread 'test_factor::test_parallel' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', tests/common/util.rs:1517:37


failures:
    test_factor::test_parallel
    test_ls::test_ls_indicator_style
    test_mv::test_mv_move_file_between_dirs
    test_mv::test_mv_move_file_into_dir
    test_mv::test_mv_move_file_into_dir_with_target_arg
    test_mv::test_mv_move_file_into_file_with_target_arg
    test_mv::test_mv_move_multiple_files_into_file
    test_mv::test_mv_multiple_files
    test_mv::test_mv_multiple_folders
    test_mv::test_mv_no_clobber
    test_mv::test_mv_numbered_if_existing_backup_existing
    test_mv::test_mv_numbered_if_existing_backup_nil
    test_mv::test_mv_overwrite_dir
    test_mv::test_mv_overwrite_nonempty_dir
    test_mv::test_mv_rename_dir
    test_mv::test_mv_replace_file
    test_mv::test_mv_same_file
    test_mv::test_mv_same_file_dot_dir
    test_mv::test_mv_same_file_not_dot_dir
    test_mv::test_mv_same_hardlink
    test_mv::test_mv_same_hardlink_backup_simple
    test_mv::test_mv_simple_backup
    test_mv::test_mv_simple_backup_with_file_extension
    test_mv::test_mv_strip_slashes
    test_numfmt::test_invalid_unit_size
    test_numfmt::test_round
    test_numfmt::test_round_with_to_unit
    test_numfmt::test_should_report_invalid_suffix_on_stdin
    test_numfmt::test_transform_without_suffix_on_input
    test_numfmt::test_valid_but_forbidden_suffix
    test_od::test_big_endian
    test_od::test_dec
    test_od::test_dec_offset
    test_od::test_f16
    test_od::test_f32
    test_od::test_f64
    test_od::test_file
    test_od::test_file_offset
    test_od::test_filename_parsing
    test_od::test_from_mixed
    test_od::test_hex16
    test_od::test_hex32
    test_od::test_hex_offset
    test_od::test_invalid_arg
    test_od::test_max_uint
    test_od::test_multibyte
    test_od::test_multiple_formats
    test_od::test_no_file
    test_od::test_no_offset

test result: FAILED. 2155 passed; 49 failed; 32 ignored; 0 measured; 3 filtered out; finished in 12.79s

error: test failed, to rerun pass `--test tests`
error: 1 target failed:
    `--test tests`
make: *** [GNUmakefile:290: test] Error 101
```

</details>

It seems like something is changed between the last release that causes permission errors. I tracked down the issue until the temp file creation but couldn't figure out what could go wrong.

To reproduce, you can fetch the latest `PKGBUILD` [here](https://gitlab.archlinux.org/archlinux/packaging/packages/uutils-coreutils/-/blob/main/PKGBUILD) and build it in a [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) (`extra-x86_64-build`).

Here is how I run the tests:

```sh
$ sed 's|"bin"|"builduser"|g' -i tests/by-util/test_{chgrp,chown}.rs

$ make test \
      PROFILE=release \
      CARGOFLAGS=--release \
      TEST_NO_FAIL_FAST="--no-fail-fast -- \
        --skip test_chown::test_big_p \
        --skip test_chgrp::test_big_p \
        --skip test_chgrp::test_big_h"
```

Not sure if the `sed` hack or skips are still necessary. Let me know if there is any suggested way to run them.

**Comment by tertsdiepraam** [comment]
Very strange that this suddenly popped up. I can't find anything in the diff between 0.0.18 and 0.0.19 that would cause this. It seems mostly due to functions in the test framework, but nothing much changed there. Just to check: are you getting the same errors without the clean chroot? Maybe there's no permission for making a tmpdir or something?

**Comment by orhun** [comment]
I just tried outside the chroot on my local machine and the tests passed. So I suspect that there might be a permission issue about creating temporary directories as you mentioned. I wonder what can we do in that case 🤔  

0.0.18 worked just fine and tests were passing.

**Comment by tertsdiepraam** [comment]
Strange... Would you have the time to do a `git bisect` on this? If we can narrow down when this changed that would help a lot.

**Comment by orhun** [comment]
Sure thing, I will look into it when I have the time. I also reached out to someone who has more info about Arch Linux chroots, he will probably show up with something soon!

**Comment by RenjiSann** [comment]
ping @orhun 
Is this still relevant today ?
Can we close the issue ?

**Comment by orhun** [comment]
hey, it seems like this is not relevant anymore, re-enabled tests in https://gitlab.archlinux.org/archlinux/packaging/packages/uutils-coreutils/-/commit/99bbe51030b6c067509fc513a6888e83dc5480ce
