### ISSUE TITLE
test_file_column_width_if_filename_contains_unicode_chars started to fail recently

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5015]
Example https://github.com/uutils/coreutils/actions/runs/5390317054/jobs/9785487685?pr=5014

```

--- TRY 3 STDERR:        coreutils::tests test_df::test_file_column_width_if_filename_contains_unicode_chars ---
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"File Mounted on"`,
 right: `"File    Mounted on"`', tests\by-util\test_df.rs:839:5

--- TRY 3 STDERR:        coreutils::tests test_df::test_type_option_with_file ---
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', tests\by-util\test_df.rs:267:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\std\src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\core\src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\core\src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f\library\core\src/option.rs:935:21
   4: tests::test_df::test_type_option_with_file
             at .\tests\by-util\test_df.rs:267:19
   5: tests::test_df::test_type_option_with_file::{{closure}}
             at .\tests\by-util\test_df.rs:262:33
   6: core::ops::function::FnOnce::call_once
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f\library\core\src\ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\core\src\ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\core\src\ops/function.rs:250:5
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\alloc\src/boxed.rs:1993:9
  10: test::run_test_in_spawned_subprocess
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\test\src/lib.rs:792:27
  11: test::test_main_static_abort
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f/library\test\src/lib.rs:185:9
  12: tests::main
             at .\tests\tests.rs:1:1
  13: core::ops::function::FnOnce::call_once
             at /rustc/36fb58e433c782e27dd41034284e157cf86d587f\library\core\src\ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cakebaker** [comment]
There are three other tests that also fail:

- test_df::test_nonexistent_file
- test_df::test_output_file_specific_files
- test_df::test_type_option_with_file
