### ISSUE TITLE
`date` panics on input `-d68888888888888sms`

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5149]
To reproduce:
```
cargo run --no-default-features --features date -- date -d68888888888888sms 
```

Error message:
```
thread 'main' panicked at '`DateTime + Duration` overflowed', /home/terts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chrono-0.4.26/src/datetime/mod.rs:991:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:2025:5
   5: core::option::Option<T>::expect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:913:21
   6: <chrono::datetime::DateTime<Tz> as core::ops::arith::Add<chrono::oldtime::Duration>>::add
             at /home/terts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chrono-0.4.26/src/datetime/mod.rs:991:9
   7: uu_date::uumain::uumain
             at ./src/uu/date/src/date.rs:230:47
   8: uu_date::uumain
             at ./src/uu/date/src/date.rs:141:1
   9: coreutils::main
             at ./src/bin/coreutils.rs:105:31
  10: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Found by the fuzzer here:
https://github.com/uutils/coreutils/actions/runs/5752324281/job/15593063244?pr=5131 (https://github.com/uutils/coreutils/pull/5131)

**Comment by tommady** [comment]
Hi may I have a chance to fix this one? Thx.

**Comment by cakebaker** [comment]
@tommady sure, go ahead :)
