### ISSUE TITLE
fmt: --goal produces different output than GNU fmt

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5162]
When using `-g`/`--goal`, the output differs between uutils fmt and GNU fmt:
```
// uutils fmt
$ cargo run fmt tests/fixtures/fmt/one-word-per-line.txt --goal=7
this is
a file
with one
word per
line

// GNU fmt
$ fmt tests/fixtures/fmt/one-word-per-line.txt --goal=7
this is a
file with one
word per line
```
A test case for this issue was added in https://github.com/uutils/coreutils/pull/5159/files

**Comment by tommady** [comment]
Hi @cakebaker 
may I give it a try?
thank you.

**Comment by cakebaker** [comment]
Sure, go ahead :)

**Comment by tommady** [comment]
hey @cakebaker 
I searched around in the issues and I could not find any.

about the uutils fmt
since the --goal option is related to the --width option,
so I noticed that the below cases are also wrong.

```bash
# uutils fmt
❯ cargo run fmt tests/fixtures/fmt/one-word-per-line.txt --goal=1
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/coreutils fmt tests/fixtures/fmt/one-word-per-line.txt --goal=1`
thread 'main' panicked at 'attempt to subtract with overflow', src/uu/fmt/src/linebreak.rs:248:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
this%

# GNU fmt
❯ fmt tests/fixtures/fmt/one-word-per-line.txt --goal=1
this is a
file with
one word
per line
```

```bash
# uutils fmt
❯ cargo run fmt tests/fixtures/fmt/one-word-per-line.txt --width=1
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/coreutils fmt tests/fixtures/fmt/one-word-per-line.txt --width=1`
thread 'main' panicked at 'attempt to subtract with overflow', /home/arch/code/xxx/coreutils/src/uu/fmt/src/fmt.rs:157:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

# GNU fmt
❯ fmt tests/fixtures/fmt/one-word-per-line.txt --width=1
this
is
a
file
with
one
word
per
line
```

the unit test case of *test_fmt_width* is incorrect too
```bash
# uutils fmt
❯ cargo run fmt tests/fixtures/fmt/one-word-per-line.txt --width=10
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/coreutils fmt tests/fixtures/fmt/one-word-per-line.txt --width=10`
this is
a file
with one
word per
line

# GNU fmt
❯ fmt tests/fixtures/fmt/one-word-per-line.txt --width=10
this is a
file with
one word
per line
```

so I am wondering due to I could not fix this PR without affecting those test cases, but if I did the fix it would be beyond this PR's scope.

please guide me on what should I do.
thanks. 🙇🏻

**Comment by tommady** [comment]
ok, got it!
thanks~

**Comment by jfinkels** [comment]
This is causing a failure in the GNU test file `tests/fmt/goal-option.sh`.
