### ISSUE TITLE
`relpath` panicked for no arguments

### ISSUE THREAD

**Issue by moonfruit** [uutils/coreutils#5300]
`relpath` panicked with no arguments:

```console
$ uname -a
Darwin localhost.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
$ sw_vers
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91
$ relpath --version
relpath 0.0.21
$ relpath
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /coreutils-0.0.21/src/uu/relpath/src/relpath.rs:31:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ RUST_BACKTRACE=1 relpath
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /coreutils-0.0.21/src/uu/relpath/src/relpath.rs:31:63
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: uu_relpath::uumain
   4: relpath::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$ RUST_BACKTRACE=full relpath
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /coreutils-0.0.21/src/uu/relpath/src/relpath.rs:31:63
stack backtrace:
   0:        0x10304a110 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ad3e9225f7521e9
   1:        0x10302f2d8 - core::fmt::write::hd596d2031660b392
   2:        0x10305c328 - std::io::Write::write_fmt::h2c992930f1478641
   3:        0x103049f34 - std::sys_common::backtrace::print::haf9902f09b134a96
   4:        0x10305c8a8 - std::panicking::default_hook::h01526266ddbcf080
   5:        0x10305cfe0 - std::panicking::rust_panic_with_hook::hf80c108ff425fa61
   6:        0x10304a65c - std::panicking::begin_panic_handler::{{closure}}::h5df3e10b49e527bd
   7:        0x10304a5f0 - std::sys_common::backtrace::__rust_end_short_backtrace::hece657cf8f4082b7
   8:        0x10305cb3c - _rust_begin_unwind
   9:        0x10306d9c0 - core::panicking::panic_fmt::hb9fc09aa98cf5e3e
  10:        0x10306da84 - core::panicking::panic::heae37f5423b5bc34
  11:        0x103038e44 - uu_relpath::uumain::h5b0ae61e2985708e
  12:        0x10303c884 - relpath::main::h46d8b60660dec395
  13:        0x103039698 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4642624805be8d88
  14:        0x10303c160 - _main
```

**Comment by sylvestre** [comment]
also, see:
https://github.com/uutils/coreutils/issues/5236
