### ISSUE TITLE
`seq 1e-9223372036854775808` should not fail

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#6234]
tested by
gnu/tests/seq/seq-precision.sh

```
$ cargo run seq 1e-9223372036854775808  
thread 'main' panicked at /home/sylvestre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bigdecimal-0.4.0/src/lib.rs:2059:21:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ /usr/bin/seq 1e-9223372036854775808
$ echo $?
0
```

**Comment by sylvestre** [comment]
Similarly, found with fuzzing:
```
$ cargo run seq 66000e000000000000000000000000000000000000000000000000000009223372036854775807
thread 'main' panicked at src/uu/seq/src/numberparse.rs:114:21:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BenWiederhake** [comment]
Duplicate of #3318, and it's definitely not a good first issue, as it requires mucking about with seq/bigdecimal internals.
