### ISSUE TITLE
tests: running the tests with `--no-default-features` no longer works

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#6273]
When I try to run the tests of a single util with `cargo test --features "cp" --no-default-features` the tests of the util itself are no longer run. Instead, the failing of two other tests is shown:
```
failures:

---- util_completion stdout ----
thread 'util_completion' panicked at tests/test_util_name.rs:214:5:
assertion `left == right` failed
  left: Some(2)
 right: Some(0)

---- util_manpage stdout ----
thread 'util_manpage' panicked at tests/test_util_name.rs:242:5:
assertion `left == right` failed
  left: Some(2)
 right: Some(0)


failures:
    util_completion
    util_manpage
```

**Comment by sylvestre** [comment]
i guess it is https://github.com/uutils/coreutils/pull/6198 by @BenWiederhake
