### ISSUE TITLE
flaky CI macos: test_install_and_strip "Wait: Timeout of '30s' reached"

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6333]
Even more tests on MacOS CI are failing for some reason. This issue is about different tests than #6275, and also a different root cause, but might still be related.

Example "IndeterminateOffset":
```
---- test_uptime::test_uptime stdout ----
run: /Users/runner/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils uptime
thread 'test_uptime::test_uptime' panicked at 'Command was expected to succeed. code: 101
stdout = 
 stderr = thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndeterminateOffset', src/uucore/src/lib/features/utmpx.rs:192:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
', tests/by-util/test_uptime.rs:18:10
```

Example "too new GNU":
```
---- test_who::test_boot stdout ----
run: gwho --version
uutils-tests-info: version for the reference coreutil 'gwho' is higher than expected; expected: 8.3, found: 9.5
run: gwho -b
run: /Users/runner/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils who -b
thread 'test_who::test_boot' panicked at 'Command was expected to succeed. code: 101
stdout = 
 stderr = thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndeterminateOffset', src/uucore/src/lib/features/utmpx.rs:192:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
', tests/by-util/test_who.rs:33:28
```

I don't know whether these are two separate issues; they appear together, so I report them together.

Seen at least in #6294 and #6142. This seems to occur very often.

Since I don't really understand our MacOS CI, I can't fix this.

**Comment by cakebaker** [comment]
The errors with `IndeterminateOffset` have been fixed in https://github.com/uutils/coreutils/pull/6413 and https://github.com/uutils/coreutils/pull/6414
