### ISSUE TITLE
Windows Rust nightly: test_ln::test_symlink_verbose started to fail with `ln: Already exists`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#7001]
```

──── TRY 3 STDERR:       coreutils::tests test_ln::test_symlink_verbose
thread 'test_ln::test_symlink_verbose' panicked at tests\by-util\test_ln.rs:383:10:
Command was expected to succeed. code: 1
stdout = 
 stderr = ln: Already exists

stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/bdc6b3de48646345549fd2fe9f62370f56e3fa56/library\std\src\panicking.rs:676
   1: core::panicking::panic_fmt
             at /rustc/bdc6b3de48646345549fd2fe9f62370f56e3fa56/library\core\src\panicking.rs:75
   2: tests::common::util::CmdResult::success
             at .\tests\common\util.rs:417
   3: tests::common::util::UCommand::succeeds
             at .\tests\common\util.rs:1782
   4: tests::test_ln::test_symlink_verbose
             at .\tests\by-util\test_ln.rs:380
   5: tests::test_ln::test_symlink_verbose::closure$0
             at .\tests\by-util\test_ln.rs:364
   6: core::ops::function::FnOnce::call_once<tests::test_ln::test_symlink_verbose::closure_env$0,tuple$<> >
             at /rustc/bdc6b3de48646345549fd2fe9f62370f56e3fa56\library\core\src\ops\function.rs:250
   7: core::ops::function::FnOnce::call_once
             at /rustc/bdc6b3de48646345549fd2fe9f62370f56e3fa56/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Seen here:
https://github.com/uutils/coreutils/actions/runs/12483954019/job/34840981058?pr=6997

Dunno if it is caused by a rustc usptream change or not

**Comment by ChrisDenton** [comment]
This is very likely an upstream issue. Unfortunately our testing appears to not be quite as robust as coreutils is in this area. I'll try to fix asap.

**Comment by sylvestre** [comment]
@ChrisDenton cool! I wasn't expecting someone from upstream seeing this bug that quickly :)

Happy that our impl of the coreutils is used to regressions :)

**Comment by ChrisDenton** [comment]
Thanks to uutils for noticing this! I hopefully [fixed](https://github.com/rust-lang/rust/commit/42591a4cc0ccfc487b5f0813a77c79137fd10eb5) the problem. It should be released in the next nightly (2024-12-27).

**Comment by sylvestre** [comment]
fixed, thanks!
